Repository krafton-jungle-AI-InterviewMate/AI-InterviewMate-FE, pull requests merged in 2023-03, with the labels that each got.

#127 feat: 유저 면접 화면 및 기능 구현
  src/App.tsx
  src/api/interview/type.ts
  src/components/interview/InterviewRadio.tsx
  src/components/interview/userInterview/InterviewerQuestionTap.tsx
  src/components/interview/userInterview/OvVideo.tsx
  src/components/interview/userInterview/UserInterviewReady.tsx
  src/components/interview/userInterview/UserInterviewStart.tsx
  src/components/interview/userInterview/UserInterviewTimer.tsx
  src/components/interview/userInterview/UserVideoComponent.tsx
  src/components/lobby/Room.tsx
  src/components/modal/room/AiRoomForm.tsx
  src/components/modal/room/UserRoomForm.tsx
  src/pages/Lobby.tsx
  src/pages/interview/InterviewEnd.tsx
  src/pages/interview/userInterview/UserInterview.tsx
  src/store/interview/atom.ts
  vite.config.ts
Labels: High

#130 fix: 면접 방 생성 팝업에서 MUI 컴포넌트 제거
  src/api/interview/type.ts
  src/components/modal/room/AiRoomForm.tsx
  src/components/modal/room/UserRoomForm.tsx
  src/main.tsx
  src/styles/GlobalStyles.tsx
Labels: bug

#132 fix: 시나리오 시연 때 발견한 버그 수정
  src/pages/interview/InterviewAi.tsx
  src/pages/interview/InterviewReady/index.tsx
  src/pages/mypage/QuestionDetails/index.tsx
Labels: bug

#133 fix: 전체적인 UI 수정 및 빌드 에러 수정
  package.json
  src/components/interview/InterviewAiContainer/InterviewAiController/AnswerModeController.tsx
  src/components/interview/InterviewAiContainer/InterviewAiController/FinishedModeController.tsx
  src/components/interview/InterviewAiContainer/InterviewAiTimer.tsx
  src/components/interview/InterviewAiContainer/InterviewComment.tsx
  src/components/interview/InterviewNameTag.tsx
  src/components/interview/InterviewResult.tsx
  src/components/layout/common/Breadcrumbs/styles.ts
  src/components/layout/common/Logo.tsx
  src/components/layout/common/ProfileButton/index.tsx
  src/components/layout/common/ProfileButton/styles.ts
  src/components/layout/nav/Nav.tsx
  src/components/layout/result/ResultDetailsLayout.tsx
  src/components/lobby/Room.tsx
  src/components/modal/lobby/RoomPasswordPopup/index.tsx
  src/components/modal/room/AiRoomForm.tsx
  src/components/modal/room/CreateRoom.tsx
  src/components/modal/room/UserRoomForm.tsx
  src/components/mypage/ProfileUpdatePopup/index.tsx
  src/components/mypage/resultDetails/ResultChartAi/index.tsx
  src/components/mypage/resultDetails/ResultChartUser/index.tsx
  src/components/mypage/resultDetails/ResultScript/index.tsx
  src/components/mypage/resultDetails/ResultTimeline/index.tsx
  src/components/mypage/resultDetails/ResultVideo/index.tsx
  src/pages/Lobby.tsx
  src/pages/Login.tsx
  src/pages/interview/InterviewAi.tsx
  src/pages/interview/InterviewEnd.tsx
  src/pages/interview/InterviewReady/InterviewerSelectModal.tsx
  src/pages/interview/InterviewReady/index.tsx
  src/pages/interview/InterviewReady/style.ts
  src/pages/mypage/Mypage.tsx
  src/pages/mypage/ResultDetails.tsx
  src/styles/common.ts
  src/styles/resultDetails.ts
  vite.config.ts
  yarn.lock
Labels: bug

#142 fix: 동영상 청크 여러 개일 때 aws api 제대로 호출되지 않던 이슈 처리
  src/components/interview/EndCommentForm.tsx
  src/components/interview/SubmitProcessingPopup/index.tsx
  src/components/modal/room/AiRoomForm.tsx
  src/components/mypage/resultDetails/ResultTimeline/ResultTimelineItem.tsx
  src/components/mypage/resultDetails/ResultTimeline/index.tsx
  src/components/mypage/resultDetails/ResultTimeline/utils.ts
  src/components/mypage/resultDetails/ResultVideo/Video.tsx
  src/components/mypage/resultDetails/ResultVideo/index.tsx
  src/hooks/queries/video.ts
  src/hooks/useInitializeInterviewState.ts
  src/pages/interview/InterviewEnd.tsx
  src/pages/mypage/ResultDetails.tsx
  src/store/interview/atom.ts
Labels: bug

#147 fix: 유저 면접 로직 문제 해결
  src/hooks/queries/mypage.ts
  src/pages/interview/InterviewEnd.tsx
  src/pages/interview/userInterview/UserInterview.tsx
Labels: bug

#149 fix: 유저 면접 로직 문제 해결
  src/components/interview/userInterview/UserInterviewStart.tsx
  src/pages/interview/InterviewEnd.tsx
  src/pages/interview/userInterview/UserInterview.tsx
Labels: bug

#150 fix: 대인면접 녹화 기능 이슈 처리
  index.html
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/manifest.json
  public/ms-icon-144x144.png
  src/components/interview/userInterview/UserInterviewStart.tsx
  src/hooks/useRecorderPermission.ts
  src/hooks/useUserRecorderPermission.ts
Labels: bug

#151 fix: 면접관 다수일 경우에 대한 음성 합성 이슈 처리(형기님 코드 반영)
  index.html
  src/hooks/useUserRecorderPermission.ts
Labels: bug

#153 fix: 방이 저장되고 면접관이 남아있는 상황에 면접자가 나갈때 면접 결과가 저장이 되지 않는 이슈 처리
  src/hooks/queries/interview.ts
  src/pages/interview/userInterview/UserInterview.tsx
Labels: bug

#154 docs: README.md 초안 작성
  README.md
  public/assets/architecture.png
  public/assets/feedback.gif
  public/assets/highlights.png
  public/assets/odap.png
  public/assets/poster.png
  public/assets/tts.gif
  public/assets/user_comment.png
  public/assets/user_interview.png
  public/logo.png
  src/lib/faceLandmarkDetection.ts
Labels: documentation
